import { normalizeConfig, type AgentProfile, type NexcodeConfig } from "./schema";

/**
 * Strings that signal a destructive or irreversible operation. While `approvalMode: "ask"`,
 * a plan containing one of these goes to human approval before it runs.
 */
export const DEFAULT_RISKY_PATTERNS: readonly string[] = [
  "rm -rf",
  "rm ",
  "Remove-Item",
  "del ",
  "rmdir",
  "git push",
  "git push --force",
  "git reset --hard",
  "git clean",
  "git branch -D",
  "deploy",
  "DROP TABLE",
  "DROP DATABASE",
  "DELETE FROM",
  "TRUNCATE",
  "ALTER TABLE",
  "format ",
  "shutdown",
  "Stop-Computer",
  "Invoke-RestMethod",
  "Invoke-WebRequest",
  "curl -X POST",
  "curl -X PUT",
  "curl -X DELETE",
  "npm publish",
  "pnpm publish",
  "docker push",
  "kubectl delete",
  "terraform apply",
  "terraform destroy",
  "mail",
  "smtp",
];

/**
 * The six built-in domain agents: the fixed core of the hybrid roster.
 * Each carries an orchestration role, and that role makes the kind of work it can take
 * BINDING. Discovered CLI agents are added alongside these, never in place of them.
 */
export const DEFAULT_AGENT_PROFILES: Readonly<Record<string, AgentProfile>> = {
  ceo: {
    id: "ceo",
    name: "CEO · Orchestrator",
    enabled: true,
    role: "operator",
    domain: "ceo",
    roleFile: "operator.md",
    connection: "cli_first",
    autonomy: "supervised",
    model: { provider: "anthropic", modelId: "claude-opus-4-8" },
    modelOverride: false,
    args: [],
    adapter: "claude",
    discovered: false,
  },
  frontend: {
    id: "frontend",
    name: "Frontend",
    enabled: true,
    role: "executor",
    domain: "frontend",
    roleFile: "executor.md",
    connection: "cli_first",
    autonomy: "supervised",
    model: { provider: "openai", modelId: "gpt-5.5" },
    modelOverride: false,
    args: [],
    adapter: "codex",
    discovered: false,
  },
  backend: {
    id: "backend",
    name: "Backend",
    enabled: true,
    role: "executor",
    domain: "backend",
    roleFile: "executor.md",
    connection: "cli_first",
    autonomy: "supervised",
    model: { provider: "anthropic", modelId: "claude-opus-4-8" },
    modelOverride: false,
    args: [],
    adapter: "claude",
    discovered: false,
  },
  security: {
    id: "security",
    name: "Security",
    enabled: true,
    role: "reviewer",
    domain: "security",
    roleFile: "reviewer.md",
    // A triggered role: not continuous or high volume, so an API key is enough.
    connection: "api_only",
    autonomy: "autonomous",
    model: { provider: "anthropic", modelId: "claude-opus-4-8" },
    modelOverride: false,
    args: [],
    discovered: false,
  },
  qa: {
    id: "qa",
    name: "QA · Test",
    enabled: true,
    role: "reviewer",
    domain: "qa",
    roleFile: "reviewer.md",
    connection: "api_only",
    autonomy: "autonomous",
    // The first and cheapest tier of the escalation chain; the chain lives under `escalation.qa`.
    model: { provider: "deepseek", modelId: "deepseek-v4-flash" },
    modelOverride: false,
    args: [],
    discovered: false,
  },
  devops: {
    id: "devops",
    name: "DevOps",
    enabled: true,
    role: "executor",
    domain: "devops",
    roleFile: "executor.md",
    connection: "api_only",
    // Never touches production autonomously: every step asks for human approval.
    autonomy: "manual",
    model: { provider: "google", modelId: "gemini-3.5-flash" },
    modelOverride: false,
    args: [],
    discovered: false,
  },
};

/**
 * The safe base used when the config file cannot be read or is corrupt.
 * It carries the same values as `resources/nexcode.config.default.json`; that file is the
 * shareable template users see, while this is the in-code last resort copy.
 */
export const FALLBACK_CONFIG: NexcodeConfig = normalizeConfig({
  version: 1,
  language: "system",
  approvalMode: "auto",
  workingDir: ".",
  dailyCallBudget: 150,
  pollSeconds: 15,
  memoryCharBudget: 8000,
  teamContextCharBudget: 30000,
  taskPromptCharBudget: 6000,
  agentTimeoutSeconds: 900,
  cliSilenceTimeoutSeconds: 300,
  autonomousConsentAcceptedAt: null,
  discoveryIgnoredAdapters: [],
  liveDiff: true,
  liveDiffIntervalMs: 2500,
  versioning: true,
  versioningRetention: 20,
  sandbox: { mode: "workspace", extraWritableDirs: [] },
  projectContext: true,
  projectContextCharBudget: 6000,
  notify: { webhookUrl: "", onComplete: true, onFailed: true },
  operator: {
    agentId: "ceo",
    roleFile: "operator.md",
    maxRounds: 6,
    maxDelegationsPerRound: 8,
    maxInfrastructureRecoveryRounds: 2,
    protocolRetries: 2,
    passFastPath: true,
  },
  resilience: { transientRetries: 2, retryBaseSeconds: 3, maxFailoverAgents: 1 },
  cliSettings: {
    claude: { model: "", modelPreferences: [], modelExclude: [] },
    codex: { model: "", reasoningEffort: "medium", serviceTier: "fast", modelPreferences: [], modelExclude: [] },
    gemini: { model: "", modelPreferences: [], modelExclude: [] },
    opencode: {
      model: "",
      modelPreferences: ["*deepseek*free*", "*free*", "*"],
      modelExclude: ["ollama/*", "lmstudio/*", "llamacpp/*", "local/*", "localhost/*"],
    },
    antigravity: { model: "", modelPreferences: [], modelExclude: [] },
  },
  skills: {
    enabled: [],
    autoMatch: true,
    catalogLimit: 12,
    maxSkillsPerAssignment: 3,
    charBudget: 2400,
    referenceCharBudget: 1200,
  },
  agents: DEFAULT_AGENT_PROFILES,
  schedules: [],
  escalation: {
    // Cheap to expensive: a simple task is solved at the first tier and only escalates when it has to.
    qa: [
      { provider: "deepseek", modelId: "deepseek-v4-flash" },
      { provider: "minimax", modelId: "minimax-m3" },
      { provider: "anthropic", modelId: "claude-sonnet-4-6" },
    ],
  },
  quota: { windowHours: 5, maxCallsPerWindow: 50 },
  riskyPatterns: DEFAULT_RISKY_PATTERNS,
});
